### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by djmtype** [amirmarmul/laravel-blade-vscode#1]
I installed this extension, but there's no blade file type to chose from, nor does the highlighting change to support blade – It just defaults to php. Secondly, in the extensions manager, I can't disable or enable this extension. The only option is to uninstall.

VS Code 1.40.2

**Comment by amirmarmul** [comment]
Thank you for using my extension. 
I've already update to fix not load on blade file and this version there is no custom config available.
