### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by tennox** [amirmarmul/laravel-blade-vscode#18]
[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

For that reason, I can't easily use your extension anymore, could you publish on OpenVSX too?
(It's typically just a matter of running `npx ovsx publish` - you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))

**Comment by amirmarmul** [comment]
Hi @tennox, thankyou for using this extension. And for your request, i've already publish in ovsx registry, you can follow this link below: [laravel-blade-vscode on OpenVSX](https://open-vsx.org/extension/amirmarmul/laravel-blade-vscode)

**Comment by tennox** [comment]
Ups, mixed up the extensions, was looking for a different one.😅
Sorry and thanks a lot 😊

**Comment by amirmarmul** [comment]
Yeah sure 👍
